# Generated by Django 4.2.20 on 2025-04-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('text', models.CharField(max_length=40, verbose_name='Описание')),
                ('access', models.CharField(max_length=15, verbose_name='Подтверждение доступности')),
                ('state', models.CharField(max_length=15, verbose_name='Остановки')),
                ('accessK', models.CharField(max_length=15, verbose_name='Доступность для колясочников')),
                ('accessV', models.CharField(max_length=15, verbose_name='Доступность для слабовидящих')),
                ('accessL', models.CharField(max_length=15, verbose_name='Доступность для слабослышащих')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
    ]
