# Generated by Django 4.2.20 on 2025-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('contact', models.CharField(max_length=30, verbose_name='Контактные данные')),
                ('ovz', models.CharField(max_length=15, verbose_name='Тип ОВЗ')),
            ],
        ),
    ]
