# Generated by Django 4.2.20 on 2025-04-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rewiews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('text', models.CharField(max_length=250, verbose_name='Отзыв')),
                ('accessK', models.CharField(max_length=15, verbose_name='Доступность для колясочников')),
                ('accessV', models.CharField(max_length=15, verbose_name='Доступность для слабовидящих')),
                ('accessL', models.CharField(max_length=15, verbose_name='Доступность для слабослышащих')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
